// Package apigen turns IBKR's OpenAPI document (api-reference.json) into api_gen.go:
// one Client method per operation. It is a pure function so a test can prove the
// checked-in file is current.
package apigen

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"regexp"
	"sort"
	"strings"
)

type param struct {
	Name     string `json:"name"`
	In       string `json:"in"`
	Required bool   `json:"required"`
}

type operation struct {
	OperationID string                `json:"operationId"`
	Summary     string                `json:"summary"`
	Description string                `json:"description"`
	Tags        []string              `json:"tags"`
	Parameters  []param               `json:"parameters"`
	RequestBody json.RawMessage       `json:"requestBody"`
	Security    []map[string][]string `json:"security"`
}

type spec struct {
	Paths map[string]map[string]json.RawMessage `json:"paths"`
}

var methods = []string{"get", "post", "put", "patch", "delete"}
var pathParam = regexp.MustCompile(`\{([^}]+)\}`)
var goKeywords = map[string]bool{"type": true, "func": true, "var": true, "range": true, "map": true, "chan": true, "go": true, "select": true, "package": true, "import": true, "interface": true, "struct": true, "default": true, "case": true, "switch": true, "return": true, "const": true, "for": true, "if": true, "else": true, "defer": true, "fallthrough": true, "goto": true, "break": true, "continue": true}

// MethodName is the Go name of an operation id: tradingOrders_submitNewOrder ->
// TradingOrdersSubmitNewOrder.
func MethodName(operationID string) string {
	var sb strings.Builder
	for _, part := range strings.FieldsFunc(operationID, func(r rune) bool { return r == '_' || r == '-' || r == '.' }) {
		sb.WriteString(strings.ToUpper(part[:1]) + part[1:])
	}
	return sb.String()
}

func ident(name string) string {
	var sb strings.Builder
	up := false
	for _, r := range name {
		switch {
		case r == '-' || r == '_' || r == '.':
			up = true
		case up:
			sb.WriteString(strings.ToUpper(string(r)))
			up = false
		default:
			sb.WriteRune(r)
		}
	}
	s := sb.String()
	if s == "" || goKeywords[s] {
		s += "_"
	}
	return s
}

func comment(sb *strings.Builder, text string) {
	for _, line := range strings.Split(strings.TrimSpace(text), "\n") {
		line = strings.TrimSpace(strings.NewReplacer("<br>", " ", "**", "", "`", "").Replace(line))
		if line != "" {
			sb.WriteString("// " + line + "\n")
		}
	}
}

// Generate returns the gofmt'd source of api_gen.go for the OpenAPI document in specJSON.
func Generate(specJSON []byte) ([]byte, error) {
	var sp spec
	if err := json.Unmarshal(specJSON, &sp); err != nil {
		return nil, err
	}
	paths := make([]string, 0, len(sp.Paths))
	for p := range sp.Paths {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	var sb strings.Builder
	sb.WriteString("// Code generated by cmd/genapi from api-reference.json. DO NOT EDIT.\n\npackage ibkr\n\nimport (\n\t\"context\"\n\t\"net/http\"\n\t\"net/url\"\n\t\"encoding/json\"\n)\n\n")
	sb.WriteString("var _ = url.PathEscape\nvar _ http.Header\n\n")

	seen := map[string]string{}
	count := 0
	for _, path := range paths {
		for _, m := range methods {
			rawOp, ok := sp.Paths[path][m]
			if !ok {
				continue
			}
			var op operation
			if err := json.Unmarshal(rawOp, &op); err != nil {
				return nil, fmt.Errorf("%s %s: %w", m, path, err)
			}
			if op.OperationID == "" {
				return nil, fmt.Errorf("%s %s has no operationId", m, path)
			}
			name := MethodName(op.OperationID)
			if prev, dup := seen[name]; dup {
				return nil, fmt.Errorf("method name %s generated twice (%s, %s)", name, prev, op.OperationID)
			}
			seen[name] = op.OperationID

			kind, scheme := "authSSO", "ssoBearer"
			if len(op.Security) > 0 {
				for s := range op.Security[0] {
					scheme = s
				}
			}
			if scheme == "oauth2Bearer" {
				kind = "authOAuth2"
			}

			var args, notes []string
			var pathExpr []string
			last := 0
			for _, loc := range pathParam.FindAllStringSubmatchIndex(path, -1) {
				pathExpr = append(pathExpr, fmt.Sprintf("%q", path[last:loc[0]]))
				pn := ident(path[loc[2]:loc[3]])
				pathExpr = append(pathExpr, "url.PathEscape("+pn+")")
				args = append(args, pn+" string")
				last = loc[1]
			}
			if last < len(path) {
				pathExpr = append(pathExpr, fmt.Sprintf("%q", path[last:]))
			}
			var q, h []param
			for _, p := range op.Parameters {
				switch p.In {
				case "query":
					q = append(q, p)
				case "header":
					h = append(h, p)
				}
			}
			callQuery, callBody, callHdr := "nil", "nil", "nil"
			if len(q) > 0 {
				args = append(args, "query url.Values")
				callQuery = "query"
				var names []string
				for _, p := range q {
					n := p.Name
					if p.Required {
						n += " (required)"
					}
					names = append(names, n)
				}
				notes = append(notes, "query: "+strings.Join(names, ", "))
			}
			if len(h) > 0 {
				args = append(args, "headers http.Header")
				callHdr = "headers"
				var names []string
				for _, p := range h {
					names = append(names, p.Name)
				}
				notes = append(notes, "headers: "+strings.Join(names, ", "))
			}
			if len(op.RequestBody) > 0 && string(op.RequestBody) != "null" {
				args = append(args, "body any")
				callBody = "body"
			}

			if op.Summary != "" {
				comment(&sb, name+" - "+op.Summary+".")
			} else {
				comment(&sb, name+".")
			}
			if op.Description != "" {
				comment(&sb, op.Description)
			}
			comment(&sb, strings.ToUpper(m)+" "+path+" ["+scheme+"]")
			for _, n := range notes {
				comment(&sb, n)
			}
			all := append([]string{"ctx context.Context"}, args...)
			fmt.Fprintf(&sb, "func (c *Client) %s(%s) (json.RawMessage, error) {\n", name, strings.Join(all, ", "))
			fmt.Fprintf(&sb, "\treturn c.call(ctx, http.Method%s, %s, %s, %s, %s, %s)\n}\n\n",
				strings.ToUpper(m[:1])+m[1:], strings.Join(pathExpr, " + "), callQuery, callBody, callHdr, kind)
			count++
		}
	}
	fmt.Fprintf(&sb, "// OperationCount is the number of operations generated from api-reference.json.\nconst OperationCount = %d\n", count)
	out, err := format.Source([]byte(sb.String()))
	if err != nil {
		return nil, fmt.Errorf("gofmt generated source: %w", err)
	}
	return bytes.TrimRight(out, "\n"), nil
}
